### ISSUE TITLE
Support Dual Licensing

### ISSUE THREAD

**Issue by bradrydzewski** [indieopensource/paid-license#1]
I would probably categorize 3 types of business models that I have seen for software sales:

1. closed source
2. open core
3. open source, copy left, dual license

I think this license addresses 1 and 2, but it might be nice to have an optional clause that can easily be added or removed that waives any copyleft requirements if specified in the open source or open core license. This is especially true for anyone using your Parity or Shared Component Licenses.

It would be cool if there was a variant of this license with the clause added, like `paid-license` and `paid-dual-license`, similar to multiple variants of the creative commons license. Similar to what I mentioned in https://github.com/indieopensource/support-contract/issues/7

**Comment by kemitchell** [comment]
I agree that this license should make support for dual licensing explicit.
