### ISSUE TITLE
Sample Order Form

### ISSUE THREAD

**Issue by sudhirj** [indieopensource/paid-license#6]
The license prominently references an order form - would that be a separate legal document or just the usual invoice / purchase order? 

Would be great to have an order form template, or maybe just the list of things that it should have so the license references aren’t left dangling.

**Comment by kemitchell** [comment]
@sudhirj "order form" is a generic term there for the document that sets out what's being licensed, for how much, under what payment terms, and so on. Traditionally, those are offers or other ordering documents that salespeople send to potential leads, with signatures blocks. More recently, they're often the offers made on websites during a checkout process.

I'm not against providing a template or example, through these documents are very frequently styled up and "branded" by the vendor.

A checklist of things the license terms expect from the order from is a great place to start.
